apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
spec:
  template:
    spec:
      containers:
        - name: ollama
          resources:
            requests:
              cpu: 500m
              memory: 4Gi
            limits:
              cpu: "4"
              memory: 12Gi
              nvidia.com/gpu: "1"
